issue #90
TruongTheTan/FlastSurvival pull request #119
Opened 2023-03-20 17:32 UTC by anh3214

https://user-images.githubusercontent.com/92512753/226421155-ded9478c-f0a0-41b8-970f-11d7b9616a57.mp4

2023-03-21 11:06 UTC, Seth-Etherald commented
Sao không để nhân vật nhận exp theo loại địch luôn mà vẫn để fix cứng?

2023-03-21 17:00 UTC, TruongTheTan requested changes

2023-03-21 17:00 UTC, TruongTheTan commented on Assets/Scripts/PrefabControllers/EnemyController.cs
đổi param của OnExpChanged() sang điểm của mỗi con quái

2023-03-22 00:29 UTC, Seth-Etherald approved these changes
Có vẻ ổn đấy.

2023-03-22 04:44 UTC, TruongTheTan approved these changes
ok

2023-03-22 04:44 UTC, merged